-- Script para criar a tabela tipos_fornecedores
-- Execute este script no SQL Editor do Supabase

BEGIN;

-- Criar a tabela tipos_fornecedores se não existir
CREATE TABLE IF NOT EXISTS tipos_fornecedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE,
  descricao TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Comentários na tabela
COMMENT ON TABLE tipos_fornecedores IS 'Tabela para armazenar tipos/categorias de fornecedores';
COMMENT ON COLUMN tipos_fornecedores.id IS 'Identificador único do tipo de fornecedor';
COMMENT ON COLUMN tipos_fornecedores.nome IS 'Nome do tipo de fornecedor';
COMMENT ON COLUMN tipos_fornecedores.descricao IS 'Descrição detalhada do tipo de fornecedor';
COMMENT ON COLUMN tipos_fornecedores.created_at IS 'Data e hora de criação do registro';
COMMENT ON COLUMN tipos_fornecedores.updated_at IS 'Data e hora da última atualização do registro';

-- Índices para melhorar performance
CREATE INDEX IF NOT EXISTS idx_tipos_fornecedores_nome ON tipos_fornecedores(nome);

-- Trigger para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION trigger_set_timestamp_tipos_fornecedores()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_timestamp_tipos_fornecedores ON tipos_fornecedores;
CREATE TRIGGER set_timestamp_tipos_fornecedores
BEFORE UPDATE ON tipos_fornecedores
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp_tipos_fornecedores();

-- Inserir dados de exemplo
INSERT INTO tipos_fornecedores (nome, descricao) VALUES
('Lentes', 'Fornecedores especializados em lentes oftálmicas'),
('Armações', 'Fornecedores de armações e óculos'),
('Equipamentos', 'Fornecedores de equipamentos ópticos e médicos'),
('Materiais', 'Fornecedores de materiais diversos para ótica'),
('Serviços', 'Prestadores de serviços especializados'),
('Produtos de Limpeza', 'Fornecedores de produtos para limpeza e manutenção'),
('Acessórios', 'Fornecedores de acessórios para óculos')
ON CONFLICT (nome) DO NOTHING;

COMMIT;

-- Verificar se a tabela foi criada e os dados inseridos
SELECT 'Tabela tipos_fornecedores criada com sucesso!' as status;
SELECT COUNT(*) as total_tipos_inseridos FROM tipos_fornecedores;
SELECT * FROM tipos_fornecedores ORDER BY nome;