-- Script para criar tabelas separadas de despesas
-- Executar no SQL Editor do Supabase

BEGIN;

-- 1. Criar tabela despesas_fixas
CREATE TABLE IF NOT EXISTS despesas_fixas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filial_id BIGINT NOT NULL REFERENCES filiais(id),
  categoria_id BIGINT REFERENCES categorias_despesas(id),
  nome VARCHAR(255) NOT NULL,
  valor DECIMAL(10,2) NOT NULL,
  periodicidade VARCHAR(20) NOT NULL DEFAULT 'mensal' CHECK (periodicidade IN ('mensal', 'bimestral', 'trimestral', 'semestral', 'anual')),
  dia_vencimento INTEGER NOT NULL CHECK (dia_vencimento >= 1 AND dia_vencimento <= 31),
  data_vencimento DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'inativo')),
  observacao TEXT,
  comprovante_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Criar tabela despesas_diversas
CREATE TABLE IF NOT EXISTS despesas_diversas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filial_id BIGINT NOT NULL REFERENCES filiais(id),
  categoria_id BIGINT REFERENCES categorias_despesas(id),
  nome VARCHAR(255) NOT NULL,
  valor DECIMAL(10,2) NOT NULL,
  data_despesa DATE NOT NULL,
  data_pagamento DATE,
  forma_pagamento VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'pago')),
  observacao TEXT,
  comprovante_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Comentários nas tabelas
COMMENT ON TABLE despesas_fixas IS 'Despesas recorrentes com periodicidade definida';
COMMENT ON COLUMN despesas_fixas.periodicidade IS 'Frequência da despesa (mensal, bimestral, etc.)';
COMMENT ON COLUMN despesas_fixas.dia_vencimento IS 'Dia do mês em que a despesa vence';
COMMENT ON COLUMN despesas_fixas.status IS 'Status da despesa fixa (ativo/inativo)';

COMMENT ON TABLE despesas_diversas IS 'Despesas pontuais e variáveis';
COMMENT ON COLUMN despesas_diversas.data_despesa IS 'Data em que a despesa foi realizada';
COMMENT ON COLUMN despesas_diversas.data_pagamento IS 'Data em que a despesa foi paga';
COMMENT ON COLUMN despesas_diversas.forma_pagamento IS 'Forma de pagamento utilizada';
COMMENT ON COLUMN despesas_diversas.status IS 'Status da despesa (pendente/pago)';

-- 4. Índices para performance
CREATE INDEX IF NOT EXISTS idx_despesas_fixas_filial_id ON despesas_fixas(filial_id);
CREATE INDEX IF NOT EXISTS idx_despesas_fixas_categoria_id ON despesas_fixas(categoria_id);
CREATE INDEX IF NOT EXISTS idx_despesas_fixas_status ON despesas_fixas(status);
CREATE INDEX IF NOT EXISTS idx_despesas_fixas_data_vencimento ON despesas_fixas(data_vencimento);

CREATE INDEX IF NOT EXISTS idx_despesas_diversas_filial_id ON despesas_diversas(filial_id);
CREATE INDEX IF NOT EXISTS idx_despesas_diversas_categoria_id ON despesas_diversas(categoria_id);
CREATE INDEX IF NOT EXISTS idx_despesas_diversas_status ON despesas_diversas(status);
CREATE INDEX IF NOT EXISTS idx_despesas_diversas_data_despesa ON despesas_diversas(data_despesa);
CREATE INDEX IF NOT EXISTS idx_despesas_diversas_data_pagamento ON despesas_diversas(data_pagamento);

-- 5. Triggers para updated_at
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_timestamp_despesas_fixas ON despesas_fixas;
CREATE TRIGGER set_timestamp_despesas_fixas
BEFORE UPDATE ON despesas_fixas
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();

DROP TRIGGER IF EXISTS set_timestamp_despesas_diversas ON despesas_diversas;
CREATE TRIGGER set_timestamp_despesas_diversas
BEFORE UPDATE ON despesas_diversas
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();

COMMIT;

-- Verificar se as tabelas foram criadas
SELECT 'Tabelas separadas criadas com sucesso!' as status;
SELECT table_name, column_name, data_type, is_nullable
FROM information_schema.columns 
WHERE table_name IN ('despesas_fixas', 'despesas_diversas')
ORDER BY table_name, ordinal_position; 